blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/AAQrkhR
    about: Rather than open an issue, if you have a quick question or want to learn more, checkout our Discord server.
